### ISSUE TITLE
Improve prompt context

### ISSUE THREAD

**Issue by j-dunham** [j-dunham/openai-cli#8]
```[tasklist]
### Tasks
- [x] Add mechanize to set `system` directive.
- [x] Allow current chat messages to be passed in request prompt.
- [x] Add way to clear current chat messages and system directive.
```

relavant [docs](https://platform.openai.com/docs/guides/gpt/chat-completions-api)
